export { default as Pos } from './Pos'
export { default as Settings } from './Settings'
export { default as Receipts } from './Receipts'
export { default as NotFound } from './NotFound'
export { default as Info } from './Info'